mutation InsertIntoshareCollection($objects: [shareInsertInput!]!) {
  insertIntoshareCollection(objects: $objects) {
    affectedCount
    records {
      id
      share_id
      trip_id
    }
  }
}
