mutation deleteRyoteiByTripId($tripId: UUID!, $atMost: Int!) {
  deleteFromryoteiCollection(filter: { trip_id: { eq: $tripId } }, atMost: $atMost) {
    affectedCount
    records {
      id
      trip_id
    }
  }
}
