mutation deleteTripById($tripId: UUID!, $atMost: Int!) {
  deleteFromtripsCollection(filter: { id: { eq: $tripId } }, atMost: $atMost) {
    affectedCount
    records {
      id
      name
    }
  }
}
