query GetRyotei($orderBy: [ryoteiOrderBy!], $filter: ryoteiFilter) {
  ryoteiCollection(orderBy: $orderBy, filter: $filter) {
    edges {
      node {
        id
        description
        datetime
        trip_id
      }
    }
  }
}
