mutation updateshareCollection($objects: shareUpdateInput!, $filter: shareFilter!) {
  updateshareCollection(set: $objects, filter: $filter) {
    affectedCount
    records {
      id
      share_id
      trip_id
    }
  }
}
