name = "ryotei-share"
compatibility_date = "2025-07-27"
main = ".vercel/output/static/_worker.js"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"