name = "ryotei-share"
compatibility_date = "2025-07-27"
main = ".vercel/output/static/_worker.js"
compatibility_flags = ["nodejs_compat",  "streams_enable_constructors"]

[build]
command = "npm run pages:build"

[env.production]
vars = { NODE_ENV = "production", LOG_LEVEL = "debug" }

[durable_objects]
bindings = []

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"